### PR TITLE
[Feature/Enhancement] - Prey system rework (CPP) + Hunting task system

### LINKED ISSUE #502: [Bug]: Multiple preys on one monster
### What happened?

You can select the same monster for more than one slot using the 5 prey cards. Stacking multiple of the same prey won't work, but you can use attack + defense + exp for example and they will all work.
ezgif com-gif-maker

### How to Reproduce?

1. Open prey window
2. Use cards to open several monster lists but do not select any
3. Mark the same monster
4. Confirm prey

### Relevant log output

_No response_

### Attach any relevant file

_No response_

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 7, Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by marcosvf132**
# Prey and hunting task
image

# Description

- This PR is a complementation of this Canary PR https://github.com/opentibiabr/canary/pull/172

- Complete rewrite of old prey system from **LUA** to **CPP** and implementation of **Hunting tasks system**.

- Do not test with GOD char or with low amount of creatures registered on bestiary. The PR already include the necessary amount of then.

### **Actual**

Innexistent code for hunting task system and a incomplete prey system.

### **Expected**

Addition of hunting task system and entire rework of prey system. All working on CPP with few LUA integration.

## Type of change

  - [x] Bug fix (non-breaking change which fixes an issue)
  - [x] New feature (non-breaking change which adds functionality)
  - [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [x] This change requires a documentation update

## How Has This Been Tested

Just insert changes and run the server. Do not test it with GOD characte because it won't work as properly.

# Issues
Resolves #502

## Checklist

  - [x] My code follows the style guidelines of this project
  - [x] I have performed a self-review of my own code
  - [x] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [x] I have made corresponding changes to the documentation
  - [x] My changes generate no new warnings
  - [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by guispiller — CHANGES_REQUESTED** [review]
Just tested this PR with the Canary PR, and had these problems:

**Prey System:**
- I can buy several times the 3rd Prey Slot;
- When I buy Prey Wildcards from the shop, I need to logout my character to update these wildcards in Prey System Menu;
- Loot bonus is not showing when kill a creature (it need to show loot message + prey bonus % loot);
- XP Bonus is not working - show the following message:
[2022-04-03 13:01:47.436] [error] Lua script error:
scriptInterface: [Event Interface]
scriptId: [data/events/scripts/player.lua:Player@onGainExperience]
timerEvent: []
 callbackId:[]
function: []
error [data/events/scripts/player.lua:680: attempt to index global 'player' (a nil value)
stack traceback:
        [C]: in function '__index'
        data/events/scripts/player.lua:680: in function <data/events/scripts/player.lua:654>]

- When you select the monster "Many Faces" from the prey list, the client crashes. Only on a player account, on GOD account this doesn't happen. Debug info: Unhandled exception at 0x75EFB812 in 127.0.0.1_client.exe: Microsoft C++ exception: std::invalid_argument at memory location 0x00AFC958.

**Hunting Task System:**
- After finishing a task, the window with monsters uploads with one missing monster:
image
- After finishing a task, The buttons are ready to be clicked to reload monsters, but you can't accept or start a new task (On click, it shows : you need to wait to select a new creature)
- When you are on a task, the button to cancel it shows it costs 2gp, but when you click on it, it says cost 1600gp.

**Comment by marcosvf132** [comment]
> Just tested this PR with the Canary PR, and had these problems:
> 
> **Prey System:**
> 
> * I can buy several times the 3rd Prey Slot;
> * When I buy Prey Wildcards from the shop, I need to logout my character to update these wildcards in Prey System Menu;
> * Loot bonus is not showing when kill a creature (it need to show loot message + prey bonus % loot);
> * XP Bonus is not working - show the following message:
>   [2022-04-03 13:01:47.436] [error] Lua script error:
>   scriptInterface: [Event Interface]
>   scriptId: [data/events/scripts/player.lua:Player@onGainExperience]
>   timerEvent: []
>   callbackId:[]
>   function: []
>   error [data/events/scripts/player.lua:680: attempt to index global 'player' (a nil value)
>   stack traceback:
>   [C]: in function '__index'
>   data/events/scripts/player.lua:680: in function <data/events/scripts/player.lua:654>]
> * When you select the monster "Many Faces" from the prey list, the client crashes. Only on a player account, on GOD account this doesn't happen. Debug info: Unhandled exception at 0x75EFB812 in 127.0.0.1_client.exe: Microsoft C++ exception: std::invalid_argument at memory location 0x00AFC958.
> 
> **Hunting Task System:**
> 
> * After finishing a task, the window with monsters uploads with one missing monster:
>   image
> * After finishing a task, The buttons are ready to be clicked to reload monsters, but you can't accept or start a new task (On click, it shows : you need to wait to select a new creature)
> * When you are on a task, the button to cancel it shows it costs 2gp, but when you click on it, it says cost 1600gp.

Thank you for you feedback about this PR, i appreciate it very much!! All of your reports has been fixed with the exception of two things:
- I had no crash when selecting the creature many faces with regular char or GOD char. Both worked with no exception at all.
image



- You pointed that after claiming the task hunting reward it was blocking you from choosing another monters, but thats how it should work. As it's described on tibia WIKI, you can claim your slot reward only once per server-save. The same is implemented on this PR, with the possibility to customize that time what i named as 'task hunting exhaust'. It's an option on the config.lua
image

On this second one, following by your report, i had introduced something like a 'timer' on the message dialog to help the player to understand and know how many minutes he have to wait before he is allowed to select a new creature on that slot.


If you have found any more issues on the PR, please let me know here on the comments. Thank you!!

**Comment by guispiller** [comment]
Just tested again, with your modifications, and discovered new things:

- Prey XP bonus: It's miscalculating the XP bonus. Example: a monster that gives me 166 exp without active XP prey, is giving me 19 exp when i activate the prey;
- Store: I can still buy the 3rd prey slot more than once;
- Store: There's no 3rd hunting task slot to sell on the store;

**Hunting Task System**
I was looking at some videos on youtube of Tibia Global, and found out this, that could be an enhancement to this system:
- When clicking to complete a task, this message shows on the screen:
image

- After this message, the buttons stay unclickable, and shows it's exhausted until next server save:
image

- Here's the video if you want to take a look: https://youtu.be/Ba0nztaEjMw?t=999

**Many Faces Crash**
After testing a lot of combinations, just found out how to reproduce the Many faces Crash on prey slot:
1. Open prey dialog
2. Select any monster on the second prey slot
3. Select any monster on the first prey slot
4. Free reroll the first slot
5. On the first slot, choose to select a monster from cards list, and select many faces. When you confirm, the client crashes.
Tested that crash with, 7 characters, that happens all the time. After the crash, the character can't login anymore.
If you can't reproduce, I can show you a video.

**Trainers Enhancement**
- Another improvement that can be done, is to block Prey's time when you are on Trainers. The same way that you don't lose stamina when you are on the Trainers, your prey time should not decrease.

If you have any questions, please let me know. Thank you

**Comment by guispiller** [comment]
Just kept 2 hours running to test the locks too. Locking preys and automatic rerolling are fine, but when you don't lock any prey and the time runs out, it gets back to the initial monster choice, but with one less monster:
image

**Comment by marcosvf132** [comment]
- The missing monster on the grid is not an issue on the code, it just how the system was made to work. But on my recent researchs i found out that even on prey should be a screen showing that it should be desactivated when the prey bonus has expired, and the player can reactivate it by rerolling the list. Just changed it on last commit.

- The crash on Many Faces was fixed too on the last commit of Canary PR.

- The experience calculus was also fixed on Canary PR.

- Searching deeper on forums i found that the prey timer should be something like the stamina system and not 'battle time' just like it was on the PR, already changed that. So training on monks or any other creature and not gaining exp from it wont decrease prey time anymore.

Is there anymore issues that you have found and i should fix it?

**Comment by guispiller** [comment]
Hello, it's me again x)

Checked again, now the Prey Timer never decreases. Tested hunting for 13 minutes, the stamina timer decreased, but prey timer stand still in 2:00. I don't know if it's visual bug or it isn't decreasing.

All the other issues were fixed btw
Thanks a lot

**Comment by marcosvf132** [comment]
> Hello, it's me again x)
> 
> Checked again, now the Prey Timer never decreases. Tested hunting for 13 minutes, the stamina timer decreased, but prey timer stand still in 2:00. I don't know if it's visual bug or it isn't decreasing.
> 
> All the other issues were fixed btw Thanks a lot

Time is decreasing with no problem at all here. Make sure you have the last commit of this PR https://github.com/opentibiabr/otservbr-global/pull/480/commits/4c449cdf63d5d0e06c2eb4eaf29a198fe69970c1
image

**Review by guispiller — APPROVED** [review]
System 100% working. Thanks for contribution

**Review by dudantas — APPROVED** [review]

**Pull request merged**
