### PR TITLE
Fix the new frontier quest

### PR DESCRIPTION
**Pull request by murilo09**
# Description

Rework The New Frontier Quest - Mission 05, based on [Mission 05](https://tibia.fandom.com/wiki/The_New_Frontier_Quest#Mission_05:_Getting_Things_Busy). Some NPCs transcriptions are wrong.

Remove conflicting AID in The New Frontier Quest (Mission 09) with Custom Map.

And a small fix in how Mortal Kombat Lever handle the players trying to enter.

Remove AID and UID from Positions:
- [x] 33004, 31540, 0
- [x] 33005, 31540, 0
- [x] 33021, 31536, 4
- [x] 33021, 31536, 6
- [x] 33053, 31020, 7
- [x] 33345, 31116, 7
- [x] 33165, 31249, 11
- [x] 33170, 31248, 11

These AID were not previously removed
- [x] 32515, 31927, 7
- [x] 32474, 31947, 7
- [x] 32458, 31997, 7

### **Actual**

Conflicting AID with Custom Map

## Fixes

This issues was reported on Discord

## Type of change

Please delete options that are not relevant.

  - [X] Bug fix (non-breaking change which fixes an issue)

## Checklist

  - [X] My code follows the style guidelines of this project
  - [X] I have performed a self-review of my own code
  - [X] I checked the PR checks reports
  - [X] My changes generate no new warnings

### CODE REVIEW

**Comment by majestyotbr** [comment]
Tested, working. The actionid was already removed from position 33053, 31020, 7.

**Review by majestyotbr — APPROVED** [review]

**Comment by majestyotbr** [comment]
You need to migrate the quest to position and remove the actionid from the startup tables.

**Review by majestyotbr — CHANGES_REQUESTED** [review]
You need to migrate the quest to position and remove the actionid from the startup tables.

**Review by majestyotbr — APPROVED** [review]

**Review by dudantas — CHANGES_REQUESTED** [review]
Please change the indentation back to tab.

**Pull request merged**
