### PR TITLE
Webhook expansion

### PR DESCRIPTION
**Pull request by UReddington**
This PR allows to add a new URL to send data with the webhooks (in case that he adds special channels for new functions). Possible usages;
- If you want to track your raids on a certain channel, this PR allows you to do that
- If you want to track your announcements on a channel, this PR allows you to do that

And so on

### CODE REVIEW

**Comment by MajestyOTBR** [comment]
Can you post a example? Thanks.

**Comment by UReddington** [comment]
```
announcementChannels = {
	["serverAnnouncements"] = "url",
	["raids"] = "url",
	["player-kills"] = "url",
}

Webhook.specialSend("Server save", message, WEBHOOK_COLOR_WARNING, announcementChannels[""serverAnnouncements])
```

**Comment by MajestyOTBR** [comment]
I think it's good to add a lua file in data/scripts with:
```
-- Sends Discord webhook special notifications.
-- The URL layout is https://discord.com/api/webhooks/:id/:token
-- Leave empty if you wish to disable.
announcementChannels = {
    ["serverAnnouncements"] = "",
    ["raids"] = "",
    ["player-kills"] = "",
}
-- Example of notification:
-- Webhook.specialSend("Server save", message, WEBHOOK_COLOR_WARNING, announcementChannels["serverAnnouncements"])
```

**Comment by MajestyOTBR** [comment]
Tested, it's working.

I think it's good to add a lua file in data/scripts with:
```
-- Sends Discord webhook special notifications.
-- The URL layout is https://discord.com/api/webhooks/:id/:token
-- Leave empty if you wish to disable.
announcementChannels = {
    ["serverAnnouncements"] = "",
    ["raids"] = "",
    ["player-kills"] = "",
}
-- Example of notification:
-- Webhook.specialSend("Server save", message, WEBHOOK_COLOR_WARNING, announcementChannels["serverAnnouncements"])
```

**Review by MajestyOTBR — APPROVED** [review]

**Pull request merged**
