### PR TITLE
Added feaster of souls and grave danger bosses

### PR DESCRIPTION
**Pull request by mnapolitano01**
Adicionado:
- Acesso porta dos falcons pelo freequests
- Acesso aos bosses da grave danger pelo freequests
- Bosses da Grave Danger e Feaster of Souls em seus respectivos lugares e alavancas.
- Adicionado stepin em vengoth para o caminho da soulwar, e bosses da feaster of souls

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### **Actual**

Do this and that doesn't happens

### **Expected**

Do this and that happens

## Fixes

\# (issue)

## Type of change

Please delete options that are not relevant.

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [ ] Test A
  - [ ] Test B

**Test Configuration**:

  - Server Version:
  - Client:
  - Operating System:

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Enois90 — APPROVED** [review]

**Review by Sh3Ns — APPROVED** [review]
Very good thanks for the contribution.

**Comment by travisani** [comment]
Achei um problema nos boss levers.
```
Caso possua um time lutando contra o BOSS e alguem do lado de fora tentar puxar a alavanca.
O script vai verificar se há alguem na sala, identificar e remover o boss e os players.
idenpendente do tempo.

Função:
		-- Check if a team currently inside the boss room
		local specs, spec = Game.getSpectators(config.centerRoom, false, false, 14, 14, 13, 13)
		for i = 1, #specs do
			spec = specs[i]
			if spec:isPlayer() then
				player:sendTextMessage(MESSAGE_EVENT_ADVANCE, "There's someone fighting with ".. config.bossName ..".")
				return true
			end
			spec:remove()
		end
```

**Comment by guispiller** [comment]
> Achei um problema nos boss levers.
> 
> ```
> Caso possua um time lutando contra o BOSS e alguem do lado de fora tentar puxar a alavanca.
> O script vai verificar se há alguem na sala, identificar e remover o boss e os players.
> idenpendente do tempo.
> 
> Função:
> 		-- Check if a team currently inside the boss room
> 		local specs, spec = Game.getSpectators(config.centerRoom, false, false, 14, 14, 13, 13)
> 		for i = 1, #specs do
> 			spec = specs[i]
> 			if spec:isPlayer() then
> 				player:sendTextMessage(MESSAGE_EVENT_ADVANCE, "There's someone fighting with ".. config.bossName ..".")
> 				return true
> 			end
> 			spec:remove()
> 		end
> ```

Estou fazendo rework nesse PR e junto irei adicionar mais outros bosses. Será feito rework seguindo a mecanica da alavanca adicionada no PR #355 . Assim que mergearmos esse PR da lever, e rework das storages, subo esse PR dos bosses arrumado

**Comment by travisani** [comment]
Realmente, não tinha visto este metodo nos pulls.
Vou fazendo neste modelo e testando.

Parece bom,

**Comment by majestyotbr** [comment]
@guispiller will open a new pull request for this.

**Comment by majestyotbr** [comment]
Thanks for your contribution. @guispiller will open a new pull request for this.

**Pull request closed without merging**
