### PR TITLE
Fix restructuring storages quests

### PR DESCRIPTION
**Pull request by sircurse**
# Description

Fix to the new quest structure, where I chose a bad storage value that cannot be used by the system, causing tables to not load the storages IDs correctly.

## Checklist

  - [x] My code follows the style guidelines of this project
  - [x] I have performed a self-review of my own code
  - [x] I checked the PR checks reports
  - [x] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [x] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by rigis1 — APPROVED** [review]
On new set up i don't have any issue, i'll test now on old one.

**Comment by cblade-gpt** [comment]
there is many other files that are forgotten like the frontier quest [actions/movements] needs to change from Storage.TheNewFrontier to Storage.Quest.U8_54.TheNewFrontier

**Comment by rigis1** [comment]
> there is many other files that are forgotten like the frontier quest [actions/movements] needs to change from Storage.TheNewFrontier to Storage.Quest.U8_54.TheNewFrontier

in ongulf e.g. you have 
local TheNewFrontier = Storage.Quest.U8_54.TheNewFrontier

**Comment by sircurse** [comment]
> there is many other files that are forgotten like the frontier quest [actions/movements] needs to change from Storage.TheNewFrontier to Storage.Quest.U8_54.TheNewFrontier

Hi, all the scripts related to the quest itself are now based on an unique folder for each quest, this is a new standard to make it easy for troubleshooting. So all the files related to the quest you mentioned are actually inside data/scripts/quests/the_new_frontier

If you still have the old files on movements or actions, you should remove them.
PS: this is true only for quests that has been revised and the new frontier is one of that quests. More quests will be revised soon.

**Review by AdversarioV — APPROVED** [review]
After re testing this works all right

**Review by majestyotbr — APPROVED** [review]

**Review by guispiller — APPROVED** [review]

**Pull request merged**
