### PR TITLE
[Protocol] Support to client 12.72.11206

### PR DESCRIPTION
**Pull request by marcosvf132**
Client link: https://github.com/dudantas/tibia-client/tree/12.72.11206

Description
Client support 12.72.11206
Thanks to Rick (@FakeShinoda) for the help on market bytes.
Thanks to @hyresu for help with fix hireling offer

Added:
• Cyclopedia Character Stats - Bytes for cleave damage, reflect damage, perfect shot, magic shield capacity, concoctions potions
• Market -Bytes for cleave damage, reflect damage, perfect shot, magic shield capacity
• Missing creature icons

• Only protocol bytes

137640110-29cb8eab-a5e2-4566-96a8-2f698fdf95b5

## Checklist

  - [x] My code follows the style guidelines of this project
  - [x] I have performed a self-review of my own code
  - [x] I checked the PR checks reports
  - [x] I have commented my code, particularly in hard-to-understand areas
  - [x] I have made corresponding changes to the documentation
  - [x] My changes generate no new warnings
  - [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by dudantas** [comment]
> it is possible to bug using this way, I tested it with both ways and this one from the debug.

Test again, please! I made some corrections.

**Review by omeranha — APPROVED** [review]
as my tests, no debugs on client or errors.

**Review by dudantas — APPROVED** [review]

**Comment by dex-89** [comment]
@dudantas https://github.com/opentibiabr/otservbr-global/blob/bf6b0b56bfa20ac5489f04414f10b46206aab004/src/config/configmanager.cpp#L143 -> change to `1272`

**Comment by dudantas** [comment]
> @dudantas
> 
> https://github.com/opentibiabr/otservbr-global/blob/bf6b0b56bfa20ac5489f04414f10b46206aab004/src/config/configmanager.cpp#L143
> 
> -> change to `1272`

Friend, it has already been modified.

**Review by majestyotbr — APPROVED** [review]

**Comment by lichak232** [comment]
i'm testing now in production and i found a minor bug.
image
all items that need a profession.

**Comment by dudantas** [comment]
> i'm testing now in production and i found a minor bug. image all items that need a profession.

Did you make sure you put the bytes in the correct location? If you put it in the wrong order, it generates a bug.

**Comment by lichak232** [comment]
> > i'm testing now in production and i found a minor bug. image all items that need a profession.
> 
> Did you make sure you put the bytes in the correct location? If you put it in the wrong order, it generates a bug.

Sorry for delay.
If there is no such error in your case, then mine does not matter.

**Comment by gccris** [comment]
> > > i'm testing now in production and i found a minor bug. image all items that need a profession.
> > 
> > 
> > Did you make sure you put the bytes in the correct location? If you put it in the wrong order, it generates a bug.
> 
> Sorry for delay. If there is no such error in your case, then mine does not matter.

i think you probably made a mistake:
image
everything seems fine to me

**Comment by Szmycu** [comment]
it bugs store in market. when someone click on items in store then its debug. another thing is server crashing. it started after a few days do not know why. 

`I used gdb and get
Thread 2 "otbr" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7a12700 (LWP 90863)]
#0  0x00005555556d3475 in ItemAttributes::hasAttribute(itemAttrTypes) const ()
#1  0x000055555585bb46 in ItemAttributes::getExistingAttr(itemAttrTypes) const ()
#2  0x000055555585ba7c in ItemAttributes::getIntAttr(itemAttrTypes) const ()
#3  0x00005555556d352d in Item::getIntAttr(itemAttrTypes) const ()
#4  0x00005555557a897f in Item::getDecaying() const ()
#5  0x00005555557cabfd in Game::startDecay(Item*) ()
#6  0x000055555568c89a in Container::startDecaying() ()
#7  0x0000555555821022 in IOLoginData::loadPlayer(Player*, std::shared_ptr<DBResult>) ()
#8  0x000055555581a49b in IOLoginData::loadPlayerById(Player*, unsigned int) ()
#9  0x00005555559d732e in ProtocolGame::login(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocat
or<char> > const&, unsigned int, OperatingSystem_t) ()
#10 0x0000555555a1a9c5 in void std::__invoke_impl<void, void (ProtocolGame::*&)(std::__cxx11::basic_string<char, st
d::char_traits<char>, std::allocator<char> > const&, unsigned int, OperatingSystem_t), std::shared_ptr<ProtocolGame
>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, unsigned int&, OperatingSyste
m_t&>(std::__invoke_memfun_deref, void (ProtocolGame::*&)(std::__cxx11::basic_string<char, std::char_traits<char>, 
std::allocator<char> > const&, unsigned int, OperatingSystem_t), std::shared_ptr<ProtocolGame>&, std::__cxx11::basi
c_string<char, std::char_traits<char>, std::allocator<char> >&, unsigned int&, OperatingSystem_t&) ()
#11 0x0000555555a1552f in std::__invoke_result<void (ProtocolGame::*&)(std::__cxx11::basic_string<char, std::char_t
raits<char>, std::allocator<char> > const&, unsigned int, OperatingSystem_t), std::shared_ptr<ProtocolGame>&, std::
__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, unsigned int&, OperatingSystem_t&>::ty
pe std::__invoke<void (ProtocolGame::*&)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<ch
ar> > const&, unsigned int, OperatingSystem_t), std::shared_ptr<ProtocolGame>&, std::__cxx11::basic_string<char, st
d::char_traits<char>, std::allocator<char> >&, unsigned int&, OperatingSystem_t&>(void (ProtocolGame::*&)(std::__cx
x11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, OperatingSystem_t), st
d::shared_ptr<ProtocolGame>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, uns
igned int&, OperatingSystem_t&) ()
#12 0x0000555555a10f62 in void std::_Bind<void (ProtocolGame::*(std::shared_ptr<ProtocolGame>, std::__cxx11::basic_
string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, OperatingSystem_t))(std::__cxx11::basic_
string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, OperatingSystem_t)>::__call<void,
 , 0ul, 1ul, 2ul, 3ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) ()
#13 0x0000555555a0a51e in void std::_Bind<void (ProtocolGame::*(std::shared_ptr<ProtocolGame>, std::__cxx11::basic_
string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, OperatingSystem_t))(std::__cxx11::basic_
string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, OperatingSystem_t)>::operator()<,
 void>() ()
#14 0x0000555555a055f8 in void std::__invoke_impl<void, std::_Bind<void (ProtocolGame::*(std::shared_ptr<ProtocolGa
me>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, OperatingSystem
_t))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, Operatin
gSystem_t)>&>(std::__invoke_other, std::_Bind<void (ProtocolGame::*(std::shared_ptr<ProtocolGame>, std::__cxx11::ba
sic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, OperatingSystem_t))(std::__cxx11::ba
sic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, OperatingSystem_t)>&) ()
#15 0x0000555555a00680 in std::enable_if<is_invocable_r_v<void, std::_Bind<void (ProtocolGame::*(std::shared_ptr<Pr
--Type <RET> for more, q to quit, c to continue without paging--
otocolGame>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, Operati
ngSystem_t))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, 
OperatingSystem_t)>&>, void>::type std::__invoke_r<void, std::_Bind<void (ProtocolGame::*(std::shared_ptr<ProtocolG
ame>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, OperatingSyste
m_t))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, Operati
ngSystem_t)>&>(std::_Bind<void (ProtocolGame::*(std::shared_ptr<ProtocolGame>, std::__cxx11::basic_string<char, std
::char_traits<char>, std::allocator<char> >, unsigned int, OperatingSystem_t))(std::__cxx11::basic_string<char, std
::char_traits<char>, std::allocator<char> > const&, unsigned int, OperatingSystem_t)>&) ()
#16 0x00005555559fb91c in std::_Function_handler<void (), std::_Bind<void (ProtocolGame::*(std::shared_ptr<Protocol
Game>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, OperatingSyst
em_t))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, Operat
ingSystem_t)> >::_M_invoke(std::_Any_data const&) ()
#17 0x000055555580fa92 in std::function<void ()>::operator()() const ()
#18 0x000055555580f644 in Task::operator()() ()
#19 0x000055555580f83e in Dispatcher::threadMain() ()
#20 0x00005555559c02b1 in void std::__invoke_impl<void, void (Dispatcher::*)(), Dispatcher*>(std::__invoke_memfun_d
eref, void (Dispatcher::*&&)(), Dispatcher*&&) ()
#21 0x00005555559c00f4 in std::__invoke_result<void (Dispatcher::*)(), Dispatcher*>::type std::__invoke<void (Dispa
tcher::*)(), Dispatcher*>(void (Dispatcher::*&&)(), Dispatcher*&&) ()
#22 0x00005555559bfde3 in void std::thread::_Invoker<std::tuple<void (Dispatcher::*)(), Dispatcher*> >::_M_invoke<0
ul, 1ul>(std::_Index_tuple<0ul, 1ul>) ()
#23 0x00005555559bfab2 in std::thread::_Invoker<std::tuple<void (Dispatcher::*)(), Dispatcher*> >::operator()() ()
#24 0x00005555559bef7c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (Dispatcher::*)(), Dispatc
her*> > >::_M_run() ()
#25 0x00007ffff7cc6ed0 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#26 0x00007ffff7f17ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#27 0x00007ffff7b14def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
`

**Comment by doenteverde** [comment]
@marcosvf132 
will the new mechanics of the items be added? 
https://github.com/opentibiabr/canary/pull/143/files

**Comment by dudantas** [comment]
> @marcosvf132 will the new mechanics of the items be added? https://github.com/opentibiabr/canary/pull/143/files

the mechanics will probably only be added in canary anyway, we are making the last preparations for canary to be the global engine, so we will have a single source for both projects.

**Pull request merged**
