### PR TITLE
Fix an issue on reload spells

### PR DESCRIPTION
**Pull request by UReddington**
Just a fix of an issue on reload about spells that was reloading monsters instead spells.

### CODE REVIEW

**Comment by phacUFPE** [comment]
I think that the spells reload are fine, did you mean about the /reload spells ?

**Comment by UReddington** [comment]
I'm sure that's related to the reload all function, but it's still being a bug that the monsters get reloaded instead spells (not even sure if even monsters should be reloaded)

**Review by phacUFPE — CHANGES_REQUESTED** [review]
Fix compilation errors

**Comment by UReddington** [comment]
Listo

**Review by dudantas — APPROVED** [review]

**Pull request merged**
