### PR TITLE
Fix links to compilation

### PR DESCRIPTION
**Pull request by slawkens**
This is simple link fix in README.md

The links to Windows and Ubuntu/Debian compilation were not working.

I think it's self-explainatory.
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### **Actual**

Do this and that doesn't happens

### **Expected**

Do this and that happens

## Fixes

\# (issue)

## Type of change

Please delete options that are not relevant.

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [ ] Test A
  - [ ] Test B

**Test Configuration**:

  - Server Version:
  - Client:
  - Operating System:

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by majestyotbr** [comment]
In the pull request of compatibility between canary and otbr there are changes to the readme:
https://github.com/opentibiabr/otservbr-global/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
Anyway, thanks.

**Comment by slawkens** [comment]
Ok, didn't knew. 

Thanks for letting me know.

**Comment by MajestyOTBR** [comment]
If you have doubts, feel free to use our Discord Server:
https://discordapp.com/invite/3NxYnyV

**Comment by majestyotbr** [comment]
If you have doubts, feel free to use our Discord Server:
https://discordapp.com/invite/3NxYnyV

**Pull request closed without merging**
